### ISSUE TITLE
Net Standard support

### ISSUE THREAD

**Issue by muhaym** [ajsmithsw/PlacesSearchBar#13]
I see that there is a NETStandard branch, are you planning for a nuget release for the same?

**Comment by muhaym** [comment]
I believe Microsoft.Bcl.Build, Microsoft.Net.HttpClient references can be avoided. I can send a PR if necessary, or is it OK that if you are not planning to update nuget, I maintain a new nuget with updated code?

**Comment by ajsmithsw** [comment]
Hi @muhaym, yes it’s necessary to update this library to .NET Standard in order to continue compatibility with Xamarin Forms. If you have the time and are willing to contribute, please by all means raise a pull request to convert to .NET Standard (ive been struggling for some spare time to get it done).

If that goes well then yes, absolutely will be updating the nuget package as well.

Thanks
Alex

**Comment by muhaym** [comment]
I see another branch for NETStandard, what was it about?

**Comment by ajsmithsw** [comment]
Hi Arif,

I opened that branch to port the code to a .NET Standard library, but have
been doing a lot of travelling and haven’t had time to complete the work.
If you are able to update the library to .NET Standard and raise a PR, I’d
be happy to pull it in and update the nuget package.

Otherwise this code is under MIT, so if you decide to use the code in your
own project then I won’t stop you doing so, all I’d ask would be that you
included credit and a link to my repo.

I hope you choose to help with updating the existing library though :)

**Comment by muhaym** [comment]
Cool, I will be updating it this weekend :) Good work with the library

**Comment by ajsmithsw** [comment]
Issue will hopefully be resolved by https://github.com/ajsmithsw/PlacesSearchBar/pull/18
