### ISSUE TITLE
Can't get anything to show up

### ISSUE THREAD

**Issue by mmcarson** [ajsmithsw/PlacesSearchBar#2]
The bar just continues to show a loading icon and never loads any results. I am using the project exactly as is but with Keys.cs added.

**Comment by ajsmithsw** [comment]
@mmcarson do you have a valid Google Places API key?

**Comment by mmcarson** [comment]
Yes, I believe so.

**Comment by ajsmithsw** [comment]
OK thanks, I'm taking a look. Help me narrow it down a little - Are you attempting to run one of the example projects in this repository, or are you using the PlacesSearchBar library in your own .Forms project?

**Comment by mmcarson** [comment]
The example project

**Comment by johvahn2** [comment]
im having the same problem

**Comment by ajsmithsw** [comment]
@johvahn2 , @mmcarson ,

Thanks for your interest in this project. I’m happy to help where I can, but:

1. what have you tried, and what are you seeing? Don’t just try running the example projects, they were made using an old version of Forms. Have you tried installing the NuGet package into your own project and using it from there? Have you tried looking at the source code and figuring out where the problem is? What error messages are you seeing? If none, are you absolutely sure you have the right API key? Check that it’s valid by using an HTTP tool such as Postman, and look at the response you receive.
2. I published this project not to be a customer service provider, but to encourage open source contribution and use. If you find an issue or problem, see if you can solve it, then raise a pull request and contribute. Reports of ‘it’s not working’ don’t help the community. If we all contribute, we all win.


With this in mind, please check the namespaces used to declare the PlacesBar in XAML - Using a new project I needed to declare my namespaces like so to get this working:

` xmlns:custom="clr-namespace:DurianCode.PlacesSearchBar;assembly=DurianCode.PlacesSearchBar"  `

If you manage to solve the problem, great! Raise a PR so that others can benefit. If not, give detailed steps to reproduce, and paste in any stack traces and/or code that you've tried, so that myself and the community can help.

**Comment by global2** [comment]
search_bar.Components = new Components("country:au|country:nz");
not working

**Comment by ajsmithsw** [comment]
@global2 if you can figure out how to make it work, please raise a PR. Thanks
