### ISSUE TITLE
OVER_QUERY_LIMIT

### ISSUE THREAD

**Issue by AamirLashari** [ajsmithsw/PlacesSearchBar#24]

**Comment by ajsmithsw** [comment]
@AamirLashari please supply full information about your issue and ensure that your problem is caused by the library and not by something else. Please check the contributing guidelines for this repo [here](https://github.com/ajsmithsw/PlacesSearchBar/blob/master/CONTRIBUTING.md), otherwise this issue will be closed.

Thanks

**Comment by AamirLashari** [comment]
@ajsmithsw Thank You so much for your response. Actually, I was using free API for places which are only supported the limited number of request at a time. There is no such issue with the library.
I resolved this issue by upgrading my account.

**Comment by ajsmithsw** [comment]
Great news, thanks for your support 🙂
